login and logout with cookies
go-park-mail-ru/2022_2_Base pull request #1
Opened 2022-10-01 19:51 UTC by EuphoriaAbsorber

2022-10-01 21:37 UTC, TonyBlock requested changes

2022-10-01 21:37 UTC, TonyBlock commented on model/model.go
> +}
Чем это лучше стандартной error?

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +// @Router /login [post]
Ты как-то автоматом сгенерил это?

2022-10-01 21:37 UTC, TonyBlock commented on model/model.go
> +	Password string `json:"password"`
Ага, то есть мы возвращаем пароль?)

2022-10-01 21:37 UTC, TonyBlock commented on model/model.go
> +	imgsrc        string
1) практически все поля с маленькой буквы => они не вернутся с бэка
2) лучше везде оставь теги про названия полей в json. Так потом, если ты решишь переименовать какое-нибудь поле, апишка случайно не сломается

2022-10-01 21:37 UTC, TonyBlock commented on model/model.go
> +	rating        uint
Думаю, логичнее сделать рейтинг дробным

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +	myRouter.PathPrefix("/docs/").Handler(httpSwagger.WrapHandler)
За что отвечает этот хэндлер?

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +	http.ListenAndServe(":8080", myRouter)
Лучше порт и пути для хэндлеров задавать через какой-нибудь файл-конфиг. Пусть это будет просто набор переменных

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +	myRouter.PathPrefix("/docs/").Handler(httpSwagger.WrapHandler)
Какие это HTTP методы?

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +	}
Какой будет статус ответа?

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +func (api *MyHandler) GetUser(w http.ResponseWriter, r *http.Request) {
А кто может отправить такой запрос?

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +	json.NewEncoder(w).Encode(user)
Какие-то неконсистентные ответы, надо подумать над приведением к единообразию

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +	}
Хде return

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +}
Зачем?

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +}
Можно упростить себе жизнь и одновременно стать более безопасными и молодежными. Используй какой-нибудь пакет по генерации uuid

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +)
For what?

2022-10-01 21:37 UTC, TonyBlock commented on main.go
> +	//jwt "github.com/dgrijalva/jwt-go"
Если закоменчено, то убираем

2022-10-01 21:40 UTC, TonyBlock requested changes

2022-10-01 21:40 UTC, TonyBlock commented on main.go
> +	myRouter.HandleFunc("/getuser/{username}", api.GetUser)
Username уникален? Или могут быть коллизии

2022-10-04 15:34 UTC, TonyBlock requested changes

2022-10-04 15:34 UTC, TonyBlock commented on main.go
> +		log.Println("1234")
?)

2022-10-04 15:34 UTC, TonyBlock commented on main.go
> +		log.Println("1234")
???)

2022-10-04 15:34 UTC, TonyBlock commented on handlers/mainHandlers.go
> +	}
Какие статусы ответа?

2022-10-04 15:34 UTC, TonyBlock commented on handlers/mainHandlers.go
> +	}
Нет return

2022-10-04 15:34 UTC, TonyBlock commented on handlers/mainHandlers.go
> +	//http.SetCookie(w, session)
?

2022-10-04 15:34 UTC, TonyBlock commented on handlers/mainHandlers.go
> +		sessions: make(map[string]uint, 10),
Зачем второй параметр?

2022-10-04 15:34 UTC, TonyBlock commented on handlers/mainHandlers.go
> +	//&Result{Body: body}
???

2022-10-04 15:34 UTC, TonyBlock commented on handlers/userHandler.go
> +// }
?

2022-10-04 15:34 UTC, TonyBlock commented on handlers/userHandler.go
> +// }
?

2022-10-04 17:29 UTC, EuphoriaAbsorber commented on model/model.go
> +}
убрал

2022-10-04 17:31 UTC, EuphoriaAbsorber commented on main.go
> +func (api *MyHandler) GetUser(w http.ResponseWriter, r *http.Request) {
запрос для получения информации для странички профиля

2022-10-04 17:31 UTC, EuphoriaAbsorber commented on main.go
> +	myRouter.HandleFunc("/getuser/{username}", api.GetUser)
да, уникален. Это на самом деле почта

2022-10-04 17:54 UTC, EuphoriaAbsorber commented on model/model.go
> +}
Вернул)
Удобно иметь такое для передачи типа в функции для генерации swagger

2022-10-05 11:28 UTC, TonyBlock commented on main.go
> +func (api *MyHandler) GetUser(w http.ResponseWriter, r *http.Request) {
Я имею в виду, один человек может получить профиль другого?

2022-10-05 11:35 UTC, TonyBlock requested changes
Оставь еще в мр скрин того, сколько процент покрытия тестами и какой командой запускаешь

2022-10-05 17:14 UTC, merged